server:
  port: 8090

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: ruta-personas
              uri: lb://PERSONAS
              predicates:
                - Path=/personas,/personas/**

            - id: ruta-peliculas
              uri: lb://PELICULAS
              predicates:
                - Path=/peliculas,/peliculas/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: 127.0.0.1
    instance-id: 127.0.0.1:${spring.application.name}:${server.port}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG