server:
  port: 8090

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            # 1. SERVICIO USUARIO (Roles y Usuarios)
            - id: ruta-usuario
              uri: lb://usuario
              predicates:
                - Path=/roles/**, /usuarios/**

            # 2. SERVICIO INVENTARIO (Categorías y Productos)
            - id: ruta-inventario
              uri: lb://inventario
              predicates:
                - Path=/inventario/**

            # 3. SERVICIO CARRITO (Carrito y Pagos)
            - id: ruta-carrito
              uri: lb://carrito
              predicates:
                - Path=/carrito/**

            # 4. SERVICIO DESPACHO (Envíos y Verificaciones)
            - id: ruta-despacho
              uri: lb://despacho
              predicates:
                - Path=/api/envios/**, /verificaciones/**

            # 5. SERVICIO SOPORTE (Tickets)
            - id: ruta-soporte
              uri: lb://soporte
              predicates:
                - Path=/soporte/**

            # 6. SERVICIO REPORTES (Reportes)
            - id: ruta-reportes
              uri: lb://reportes
              predicates:
                - Path=/reportes/**

            # 7. SERVICIO PROMOCIONES (Promociones)
            - id: ruta-promociones
              uri: lb://promociones
              predicates:
                - Path=/promociones/**

            # 8. SERVICIO RESEÑA (Reseñas)
            - id: ruta-resena
              uri: lb://resena
              predicates:
                - Path=/resenas/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: 127.0.0.1
    instance-id: 127.0.0.1:${spring.application.name}:${server.port}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG