spring.application.name=carrito

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/carrito}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8084

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.override-with-generic-response=false

eureka.client.enabled=${EUREKA_CLIENT_ENABLED:true}
eureka.client.register-with-eureka=${EUREKA_REGISTER:true}
eureka.client.fetch-registry=${EUREKA_FETCH_REGISTRY:true}
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka}
eureka.instance.prefer-ip-address=${EUREKA_PREFER_IP_ADDRESS:false}
eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME:${spring.application.name}}
eureka.instance.instance-id=${EUREKA_INSTANCE_ID:${spring.application.name}:${server.port}}

services.inventario.base-url=${INVENTARIO_BASE_URL:http://inventario}
services.promociones.base-url=${PROMOCIONES_BASE_URL:http://promociones}

