spring.application.name=promociones

server.port=8088

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/promociones}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=${EUREKA_PREFER_IP_ADDRESS:false}
eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME:${spring.application.name}}
eureka.instance.instance-id=${EUREKA_INSTANCE_ID:${spring.application.name}:${server.port}}
